let info = [
  {
    stateName: "New South Wales",
    citiesName: [
      "Sydney",
      "Newcastle",
      "Central Coast",
      "Wollongong",
      "Maitland",
      "Blue Mountains",
      "Tweed Heads",
      "Coffs Harbour",
      "Wagga Wagga",
      "Albury",
      "Port Macquarie",
      "Tamworth",
      "Dubbo",
      "Orange",
      "Nowra - Bomaderry",
      "Queanbeyan",
      "Bathurst",
      "Lismore",
      "Bowral - Mittagong",
      "Armidale",
      "Goulburn",
      "Cessnock",
      "Nelson Bay",
      "Kurri Kurri",
      "Forster - Tuncurry",
      "Griffith",
      "Grafton",
      "Ballina",
      "Morisset - Cooranbong",
      "Broken Hill",
      "Batemans Bay",
      "Ulladulla",
      "Singleton",
      "Taree",
      "Kempsey",
      "St Georges Basin - Sanctuary Point",
      "Kiama",
      "Raymond Terrace",
      "Mudgee",
      "Lithgow",
      "Muswellbrook",
      "Inverell",
      "Merimbula",
      "Parkes",
      "Casino",
      "Byron Bay",
      "Young",
      "Gunnedah",
      "Cowra",
      "Murwillumbah",
      "Moss Vale",
      "Leeton",
      "Moree",
      "Forbes",
      "Lennox Head",
      "Deniliquin",
      "Narrabri",
      "Moama",
      "Cootamundra",
      "Yass",
      "Cooma",
      "Nambucca Heads",
      "Tumut",
      "Wauchope",
      "Yamba",
      "Glen Innes",
      "Woolgoolga",
      "Alstonville",
      "Wingham",
      "South West Rocks",
    ],
  },
  {
    stateName: "Victoria",
    citiesName: [
      "Whittlesea",
      "Melbourne",
      "Geelong",
      "Ballarat",
      "Bendigo",
      "Shepparton - Mooroopna",
      "Melton (Melbourne)",
      "Mildura",
      "Wodonga",
      "Warrnambool",
      "Sunbury (Melbourne)",
      "Traralgon",
      "Wangaratta",
      "Moe - Newborough",
      "Morwell",
      "Horsham",
      "Sale",
      "Ocean Grove - Barwon Heads",
      "Bacchus Marsh",
      "Pakenham",
      "Echuca",
      "Bairnsdale",
      "Warragul",
      "Colac",
      "Swan Hill",
      "Portland",
      "Lara",
      "Hamilton",
      "Drysdale - Clifton Springs",
      "Benalla",
      "Torquay - Jan Juc",
      "Maryborough",
      "Healesville",
      "Ararat",
      "Castlemaine",
      "Leopold",
      "Seymour",
      "Wonthaggi",
      "Stawell",
      "Drouin",
      "Kyabram",
      "Lakes Entrance",
      "Churchill",
      "Portarlington - St Leonards",
      "Cobram",
      "Gisborne",
      "Leongatha",
      "Kyneton",
      "Yarrawonga",
      "Wallan",
      "Inverloch",
      "Kilmore",
      "Cowes",
      "Bannockburn",
    ],
  },
  {
    stateName: "Queensland ",
    citiesName: [
      "Brisbane",
      "Gold Coast",
      "Sunshine Coast",
      "Townsville",
      "Cairns",
      "Toowoomba",
      "Mackay",
      "Rockhampton",
      "Hervey Bay",
      "Bundaberg",
      "Gladstone",
      "Maryborough",
      "Mount Isa",
      "Gympie",
      "Nambour",
      "Bongaree–Woorim",
      "Yeppoon",
      "Warwick",
      "Emerald",
      "Dalby",
      "Bargara–Innes Park",
      "Gracemere",
      "Kingaroy",
      "Tannum Sands–Boyne Island",
      "Highfields",
      "Airlie Beach",
      "Sandstone Point - Ningi",
      "Bowen",
      "Moranbah",
      "Ayr",
      "Charters Towers",
      "Mareeba",
      "Tamborine Mountain",
      "Innisfail",
      "Atherton",
      "Roma",
      "Gatton",
      "Gordonvale",
      "Chinchilla",
      "Beaudesert",
      "Biloela",
      "Mount Cotton",
      "Jimboomba - West",
      "Goondiwindi",
      "Beerwah",
      "Stanthorpe",
      "Kensington Grove – Regency Downs",
      "Blackwater",
      "Emu Park",
      "Ingham",
      "Oakey",
      "Port Douglas- Craiglie",
      "Jimboomba",
      "Palmwoods",
      "Yarrabilba",
      "Lowood",
      "Weipa",
      "Doonan - Tinbeerwah",
      "Landsborough",
      "Glass House Mountains",
      "Laidley",
      "Westbrook",
      "Beachmere",
      "Calliope",
      "Proserpine",
      "Nanango",
      "Sarina",
      "Walkerston",
      "Charleville",
      "Mooloolah",
      "Pittsworth",
      "Home Hill",
      "Thursday Island",
      "Woodford",
      "Cooroy",
      "Russell Island",
      "Maleny",
      "Fernvale",
      "Longreach",
      "Boonah",
      "Macleay Island",
      "Burnett Heads",
      "Cooloola Village",
      "Yarrabah",
      "Cedar Vale",
      "Logan Village",
      "Palm Island",
      "Dysart",
      "Mount Morgan",
      "St George",
      "Marian",
      "Rosewood",
      "Meringandan West",
      "Cloncurry",
      "Kuranda",
      "Tin Can Bay",
      "Tully",
      "Samford Valley - Highvale",
      "Alice River",
      "Moore Park",
      "Toogoom",
      "Murgon",
      "Clermont",
      "Oakhurst",
      "Gowrie Junction",
      "Cedar Grove",
      "Dayboro",
      "Kilcoy",
      "Yandina",
      "Hamilton Island",
      "Cooroibah",
      "Middlemount",
      "Wondai",
      "Glenview",
      "Jacobs Well",
      "Mossman",
      "Curra",
      "Cooktown",
      "Pomona",
      "Gayndah",
      "Crows Nest",
      "Kooralbyn",
      "Malanda",
      "Kingsthorpe",
      "Withcott",
      "River Heads",
      "Moura",
      "Glenwood",
      "Wyreema",
      "Doomadgee",
      "Meridan Plains",
      "Millmerran",
      "Hay Point",
      "Gleneagle",
      "Childers",
      "Barcaldine",
      "Willowbank",
      "Tolga - West",
      "Aurukun",
      "Cherbourg",
      "Esk",
      "Burrum Heads",
      "Plainland",
      "Cardwell",
      "Clifton",
      "Wongaling Beach",
      "Walloon",
      "Rainbow Beach",
      "Normanton",
      "Laidley Heights",
      "Jandowae",
      "Allingham",
      "Nelly Bay",
      "Bamaga",
      "Mundubbera",
      "Bakers Creek",
      "Cambooya",
      "Gununa",
      "Miles",
      "Tieri",
      "Collinsville",
      "Woodgate",
      "Kiels Mountain",
      "Blackall",
      "Howard",
      "Hughenden",
      "Kaimkillenbun",
      "Ravenshoe",
    ],
  },
  {
    stateName: "Western Australia",
    citiesName: [
      "Perth",
      "Bunbury",
      "Geraldton",
      "Albany",
      "Kalgoorlie-Boulder",
      "Busselton",
      "Karratha",
      "Port Hedland",
      "Broome",
      "Yanchep",
      "Esperance",
      "Margaret River",
      "Collie",
      "Dunsborough",
      "Northam",
      "Kununurra",
      "Newman",
      "Carnarvon",
      "Manjimup",
      "Pinjarra",
      "Narrogin",
      "Katanning",
      "Derby",
      "Denmark",
      "Tom Price",
      "Two Rocks",
      "Port Denison–Dongara",
      "Exmouth",
      "Harvey",
      "Donnybrook",
      "Capel",
      "York",
      "Merredin",
      "Waroona",
      "Bridgetown",
      "Mundijong",
      "Bullsbrook",
      "Drummond Cove",
      "Cowaramup",
      "Wickham",
      "Mount Barker",
      "Kambalda West",
      "Little Grove",
      "Halls Creek",
      "Jurien Bay",
      "Moora",
      "Serpentine",
      "Paraburdoo",
      "Wagin",
      "Dampier",
      "Binningup",
      "Kalbarri",
      "Augusta",
      "Boddington–Ranford",
      "Fitzroy Crossing",
    ],
  },
  {
    stateName: "South Australia",
    citiesName: [
      "Adelaide",
      "Gawler",
      "Mount Gambier",
      "Mount Barker",
      "Whyalla",
      "Murray Bridge",
      "Victor Harbor",
      "Crafers-Bridgewater",
      "Port Lincoln",
      "Port Pirie",
      "Port Augusta",
      "Goolwa",
      "Strathalbyn",
      "Nuriootpa",
      "Naracoorte",
      "Nairne",
      "Millicent",
      "Renmark",
      "Kadina",
      "Moonta",
      "Tanunda",
      "Wallaroo",
      "Berri",
      "Angle Vale",
      "Loxton",
      "Roxby Downs",
      "Clare",
      "McLaren Vale",
      "Two Wells",
      "Bordertown",
      "Kapunda",
      "Mannum",
      "Freeling",
      "Hahndorf",
      "Willunga",
      "Ceduna",
      "Normanville",
      "Williamstown",
      "Angaston",
      "Lewiston",
      "Lobethal",
      "Balaklava",
      "Kingscote",
      "Barmera",
      "Woodside",
      "Lyndoch",
      "Virginia",
      "Waikerie",
      "Balhannah",
      "Kingston SE",
      "Tumby Bay",
      "Coober Pedy",
      "Peterborough",
      "Tailem Bend",
      "Jamestown",
      "Penola",
      "Crystal Brook",
      "Mount Compass",
      "Ardrossan",
      "McLaren Flat",
      "Robe",
      "Quorn",
      "Keith",
      "Meadows",
      "Port Broughton",
      "Maitland",
      "Middleton",
      "Greenock",
      "Paringa",
      "Cowell",
      "Roseworthy",
      "Macclesfield",
      "Streaky Bay",
      "Birdwood",
      "Uraidla",
      "Summertown",
      "Burra",
      "Mallala",
      "Meningie",
      "Milang",
      "Cleve",
      "Riverton",
      "Yankalilla",
      "Minlaton",
      "Cummins",
      "Gumeracha",
      "Cockatoo Valley",
      "Coffin Bay",
      "Yorketown",
      "Wasleys",
      "Willyaroo",
      "Port MacDonnell",
      "Echunga",
      "Gladstone",
      "Mount Pleasant",
      "Hamley Bridge",
      "Kimba",
      "Eudunda",
      "Port Wakefield",
      "Pinnaroo",
      "Lameroo",
      "One Tree Hill",
      "Beachport",
      "Laura",
      "Pukatja (Ernabella)",
      "Orroroo",
      "Wudinna",
      "Houghton",
      "Kanmantoo",
      "Edithburgh",
      "Port Vincent",
      "Stansbury",
      "Callington",
      "Wilmington",
      "Nangwarry",
      "Myponga",
      "Blyth",
      "Kersbrook",
      "Springton",
      "Saddleworth",
      "Truro",
      "Amata",
      "Boston",
      "Clayton Bay",
      "Auburn",
      "Snowtown",
      "Indulkana",
      "Karoonda",
      "Elliston",
      "Tarpeena",
      "Point Turton",
      "Morgan",
      "Mount Burr",
      "Mount Torrens",
      "Mundulla",
      "Port Victoria",
      "Charleston",
      "Yalata",
      "Southend",
      "Napperby",
      "Lucindale",
      "Kalangadoo",
      "Port Germein",
      "American River",
      "Allendale East",
      "Mimili",
      "Tintinara",
      "Swan Reach",
      "Mullaquana",
      "Penneshaw",
      "Booleroo Centre",
      "Kaltjiti (Fregon)",
      "Andamooka",
      "Owen",
      "Blanchetown",
      "Bute",
      "Parham",
      "Hawker",
      "Tantanoola",
      "Coobowie",
      "Arno Bay",
      "Yahl",
      "Wirrabara",
      "Cobdogla",
      "Spalding",
      "Warooka",
      "Clarendon",
      "Coonalpyn",
      "Smokey Bay",
      "Port Neill",
      "Woomera",
      "Leigh Creek",
    ],
  },
  {
    stateName: "Tasmania",
    citiesName: [
      "Hobart",
      "Launceston",
      "Devonport",
      "Burnie",
      "Ulverstone",
      "Kingston",
      "Wynyard",
      "New Norfolk",
      "Perth- Evandale",
      "Latrobe",
      "Brighton",
      "Legana",
      "Bridgewater",
      "George Town",
      "Longford",
      "Margate",
      "Penguin",
      "Somerset",
      "Smithton",
      "Sorell",
      "Midway Point",
      "Deloraine",
      "Huonville",
      "Dodges Ferry",
      "Hadspen",
      "Scottsdale",
      "Westbury",
      "Port Sorell",
      "St Helens",
      "Turners Beach",
      "Queenstown",
      "Cygnet",
      "Bridport",
      "Sheffield",
      "Richmond",
      "Bagdad",
      "Snug",
      "Geeveston",
      "Carlton",
      "Beaconsfield",
      "Franklin",
      "Beauty Point",
      "Evandale",
      "Primrose Sands",
      "Campania",
      "Cressy",
      "Railton",
      "Bicheno",
      "Grindelwald",
    ],
  },
  {
    stateName: "Northern Territory",
    citiesName: [
      "Darwin",
      "Alice Springs",
      "Katherine",
      "Nhulunbuy",
      "Tennant Creek",
      "Galiwinku",
      "Wadeye",
      "Wurrumiyanga (Nguiu)",
      "Gunbalanya (Oenpelli)",
      "Milingimbi",
      "Ngukurr",
      "Angurugu",
      "Yulara",
      "Ramingining",
      "Jabiru",
      "Borroloola",
      "Alyangula",
      "Yuendumu",
      "Gapuwiyak",
      "Humpty Doo",
      "Yirrkala",
      "Lajamanu",
      "Minyerri",
      "Santa Teresa (Ltyentye Purte)",
      "Daguragu – Kalkarindji",
      "Howard Springs",
      "Hermannsburg",
      "Wugular (Beswick)",
      "Ampilatwatja",
      "Papunya",
      "Warruwi",
      "Ilparpa",
      "Wagait Beach – Mandorah",
      "Walungurru (Kintore)",
      "Umbakumba",
      "Milikapiti",
      "Ali Curung",
      "Kaltukatjara (Docker River)",
      "Batchelor",
      "Nganmarriyanga (Palumpa)",
      "Alpurrurulam",
      "Nauiyu Nambiyu (Daly River)",
      "Barunga",
      "Mataranka",
      "Pine Creek",
      "Pirlangimpi",
      "Mutitjulu",
      "Elliot",
      "Yarralin",
      "Timber Creek",
      "Minjilang",
      "Jilkminggan",
      "Bulman – Weemol",
      "Nyirripi",
      "Adelaide River",
      "Gunyangara",
      "Binjari",
      "Areyonga",
      "Amoonguna",
      "Willowra",
      "Atitjere",
      "Titjikala",
      "Aputula (Finke)",
      "Laramba",
      "Robinson River (Mungoorbada)",
      "Yuelamu",
      "Canteen Creek",
      "Wutunugurra",
    ],
  },
  {
    stateName: "Australian Capital Territory",
    citiesName: [
      "Belconnen",
      "Boboyan",
      "Booroomba",
      "Brayshaw",
      "Camberra",
      "Canberra",
      "Canberrah",
      "Christian Minde",
      "Cotter",
      "Cotter Hut",
      "Cuppacumbalong",
      "Duntroon",
      "Fyshwick",
      "Gibraltar",
      "Ginninderra",
      "Gudgenby",
      "Gungahha",
      "Gungahlin",
      "Hall",
      "Harman",
      "Jervis Bay",
      "Jervis Bay Territorium",
      "Jervis Bay Territory",
      "Kamberra",
      "Kambra",
      "Kanbera",
      "Kanbero",
      "Kanberr",
      "Kanbérra",
      "Khâm-phì-là",
      "Kowen",
      "Lanyon",
      "Majura",
      "Molonglo",
      "Orroral",
      "Teritórium Jervis Bay",
      "Territoire de la baie de Jarvis",
      "Territorio de Jervis Bay",
      "Território da Baía Jervis",
      "Terytorium Jervis Bay",
      "Tharwa",
      "Tidbinbilla",
      "Tuggeranong",
      "Urayarra",
      "Uriarra",
      "Weetangerra",
      "Weston",
      "Weston Creek",
      "Woden",
    ],
  },
];
module.exports = info;
