//Pass value in this code
let info = [
  {
    stateName: "Northern Territory",
    citiesName: [
      "Darwin",
      "Alice Springs",
      "Katherine",
      "Nhulunbuy",
      "Tennant Creek",
      "Galiwinku",
      "Wadeye",
      "Wurrumiyanga (Nguiu)",
      "Gunbalanya (Oenpelli)",
      "Milingimbi",
      "Ngukurr",
      "Angurugu",
      "Yulara",
      "Ramingining",
      "Jabiru",
      "Borroloola",
      "Alyangula",
      "Yuendumu",
      "Gapuwiyak",
      "Humpty Doo",
      "Yirrkala",
      "Lajamanu",
      "Minyerri",
      "Santa Teresa (Ltyentye Purte)",
      "Daguragu – Kalkarindji",
      "Howard Springs",
      "Hermannsburg",
      "Wugular (Beswick)",
      "Ampilatwatja",
      "Papunya",
      "Warruwi",
      "Ilparpa",
      "Wagait Beach – Mandorah",
      "Walungurru (Kintore)",
      "Umbakumba",
      "Milikapiti",
      "Ali Curung",
      "Kaltukatjara (Docker River)",
      "Batchelor",
      "Nganmarriyanga (Palumpa)",
      "Alpurrurulam",
      "Nauiyu Nambiyu (Daly River)",
      "Barunga",
      "Mataranka",
      "Pine Creek",
      "Pirlangimpi",
      "Mutitjulu",
      "Elliot",
      "Yarralin",
      "Timber Creek",
      "Minjilang",
      "Jilkminggan",
      "Bulman – Weemol",
      "Nyirripi",
      "Adelaide River",
      "Gunyangara",
      "Binjari",
      "Areyonga",
      "Amoonguna",
      "Willowra",
      "Atitjere",
      "Titjikala",
      "Aputula (Finke)",
      "Laramba",
      "Robinson River (Mungoorbada)",
      "Yuelamu",
      "Canteen Creek",
      "Wutunugurra",
    ],
  },
  {
    stateName: "Australian Capital Territory",
    citiesName: [
      "Belconnen",
      "Boboyan",
      "Booroomba",
      "Brayshaw",
      "Camberra",
      "Canberra",
      "Canberrah",
      "Christian Minde",
      "Cotter",
      "Cotter Hut",
      "Cuppacumbalong",
      "Duntroon",
      "Fyshwick",
      "Gibraltar",
      "Ginninderra",
      "Gudgenby",
      "Gungahha",
      "Gungahlin",
      "Hall",
      "Harman",
      "Jervis Bay",
      "Jervis Bay Territorium",
      "Jervis Bay Territory",
      "Kamberra",
      "Kambra",
      "Kanbera",
      "Kanbero",
      "Kanberr",
      "Kanbérra",
      "Khâm-phì-là",
      "Kowen",
      "Lanyon",
      "Majura",
      "Molonglo",
      "Orroral",
      "Teritórium Jervis Bay",
      "Territoire de la baie de Jarvis",
      "Territorio de Jervis Bay",
      "Território da Baía Jervis",
      "Terytorium Jervis Bay",
      "Tharwa",
      "Tidbinbilla",
      "Tuggeranong",
      "Urayarra",
      "Uriarra",
      "Weetangerra",
      "Weston",
      "Weston Creek",
      "Woden",
    ],
  },
];
module.exports = info;
